import type { NextPage } from 'next'
import Head from 'next/head'
import BannerHome from '../components/banner/bannerHome'
import { WhatIsThisProject } from '../components/home'
import RoadMap from '../components/home/roadMap'
import TryDemo from '../components/home/tryDemo'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Reward of life</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/logo.png" />
      </Head>
     <BannerHome/>
     <WhatIsThisProject/>
     <TryDemo/>
     <RoadMap/>
    </div>
  )
}

export default Home
