import type { NextPage } from 'next'
import Head from 'next/head'
import BannerHome from '../components/banner/bannerHome'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Reward of life</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <BannerHome/>
    </div>
  )
}

export default Home
